export const CHANGE_USER_ORG_TREE = 'baseData/CHANGE_USER_ORG_TREE'
export const CHANGE_USER_EXAM_ORG_TREE = 'baseData/CHANGE_USER_EXAM_ORG_TREE'
export const CHANGE_EXAM_ROOM_LIST = 'baseData/CHANGE_EXAM_ROOM_LIST'
export const CHANGE_ROUND_LIST = 'baseData/CHANGE_ROUND_LIST'
